// Pricing & inventory data seam. Bundles the canonical per-tenant JSON now (generated by the
// adapters from the live source file); the real backend (Netlify function over the canonical
// store) drops in behind getPricingData() later — same return shape.

import mtConfig from "@/data/montitrentini/client.config.json";
import mtCatalog from "@/data/montitrentini/catalog.json";
import mtInventory from "@/data/montitrentini/inventory.json";
import mtCommitments from "@/data/montitrentini/commitments.json";

const BUNDLES = {
  montitrentini: { config: mtConfig, catalog: mtCatalog, inventory: mtInventory, commitments: mtCommitments },
};

const USE_MOCK = (import.meta.env.VITE_PRICING_BACKEND || "mock") === "mock";

/** Canonical pricing/inventory bundle for a tenant. Null if none configured. */
export function getPricingData(resolved) {
  if (USE_MOCK) return BUNDLES[resolved.id] || null;
  // Real adapter (deferred): GET /.netlify/functions/pricing?tenant=<id>
  return null;
}

// Captured movement history (sold + missed) lives client-side until the backend lands —
// same key as the static portal so a rep's captures carry over.
const LEDGER_KEY = "mt-movement-ledger";
export function loadLedger() {
  try { return JSON.parse(localStorage.getItem(LEDGER_KEY)) || []; } catch { return []; }
}
export function appendLedger(records) {
  const led = loadLedger();
  led.push(...records);
  try { localStorage.setItem(LEDGER_KEY, JSON.stringify(led)); } catch { /* quota */ }
  return led;
}
