// Pricing & inventory data seam. Bundles the canonical per-tenant JSON now (generated by the
// adapters from the live source file); the real backend (Netlify function over the canonical
// store) drops in behind getPricingData() later — same return shape.

import mtConfig from "@/data/montitrentini/client.config.json";
import mtCatalog from "@/data/montitrentini/catalog.json";
import mtInventory from "@/data/montitrentini/inventory.json";
import mtCommitments from "@/data/montitrentini/commitments.json";

const BUNDLES = {
  montitrentini: { config: mtConfig, catalog: mtCatalog, inventory: mtInventory, commitments: mtCommitments },
};

// Backend switch. "mock" (default) = use the bundled JSON only. "function" = also pull LIVE
// inventory at runtime from /.netlify/functions/inventory (written by the weekly sync), with
// the bundled inventory as offline fallback — no app rebuild needed when stock changes.
export const PRICING_BACKEND = import.meta.env.VITE_PRICING_BACKEND || "mock";

/** Canonical pricing/inventory bundle for a tenant. Always the bundled snapshot (config +
 *  catalog + commitments + last-known inventory). This is the instant, offline-safe base;
 *  live inventory hydrates over it via fetchInventory(). Null if the tenant isn't configured. */
export function getPricingData(resolved) {
  return BUNDLES[resolved.id] || null;
}

/** Runtime inventory fetch (no rebuild). Resolves to the canonical inventory object, or null
 *  when the backend is "mock", the tenant has no live data yet, or the network/Blobs is down —
 *  in every null case the caller simply keeps the bundled inventory. Safe to call always. */
export async function fetchInventory(tenantId) {
  if (PRICING_BACKEND === "mock") return null;
  try {
    const res = await fetch(`/.netlify/functions/inventory?tenant=${encodeURIComponent(tenantId)}`,
      { headers: { Accept: "application/json" } });
    if (!res.ok) return null;
    const data = await res.json();
    return data && data.inventory ? data.inventory : null;
  } catch {
    return null;
  }
}

// Captured movement history (sold + missed) lives client-side until the backend lands —
// same key as the static portal so a rep's captures carry over.
const LEDGER_KEY = "mt-movement-ledger";
export function loadLedger() {
  try { return JSON.parse(localStorage.getItem(LEDGER_KEY)) || []; } catch { return []; }
}
export function appendLedger(records) {
  const led = loadLedger();
  led.push(...records);
  try { localStorage.setItem(LEDGER_KEY, JSON.stringify(led)); } catch { /* quota */ }
  return led;
}
